### ISSUE TITLE
HELP with some error

### ISSUE THREAD

**Issue by thiagocasti** [Kartoffel0/Mokuro2Pdf#6]
The error is not in the script, i think is just some library with mini_magick, it just dosen't recognize me  png, jpg or any type of images it just throws me this:

Processing death_note_01...
/home/peralta/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/mini_magick-4.12.0/lib/mini_magick/image.rb:221:in `rescue in validate!': `magick identify /tmp/mini_magick20240508-49032-bacb61.png` failed with status: 1 and error: (MiniMagick::Invalid)
identify: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/746.

	from /home/peralta/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/mini_magick-4.12.0/lib/mini_magick/image.rb:218:in `validate!'
	from /home/peralta/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/mini_magick-4.12.0/lib/mini_magick/image.rb:131:in `block in create'
	from <internal:kernel>:90:in `tap'
	from /home/peralta/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/mini_magick-4.12.0/lib/mini_magick/image.rb:130:in `create'
	from /home/peralta/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/mini_magick-4.12.0/lib/mini_magick/image.rb:34:in `read'
	from /home/peralta/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/mini_magick-4.12.0/lib/mini_magick/image.rb:108:in `block in open'
	from /home/peralta/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/mini_magick-4.12.0/lib/mini_magick/image.rb:108:in `open'
	from /home/peralta/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/mini_magick-4.12.0/lib/mini_magick/image.rb:108:in `open'
	from /home/peralta/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/mini_magick-4.12.0/lib/mini_magick/image.rb:108:in `open'
	from Mokuro2Pdf.rb:195:in `block (2 levels) in <main>'
	from Mokuro2Pdf.rb:175:in `each'
	from Mokuro2Pdf.rb:175:in `block in <main>'
	from Mokuro2Pdf.rb:169:in `each'
	from Mokuro2Pdf.rb:169:in `<main>'

HELP i'm not so techy so i dont know how to fix this

**Comment by Kartoffel0** [comment]
Are you using Linux by any chance?

**Comment by thiagocasti** [comment]
Yes, i am using pop os

**Comment by thiagocasti** [comment]
Ok the problem is solved idk what i did, i just know i got to uninstall everything and it was a pain to uninstall imagemagick since i installed source version and then i copy your  commands on the collab notebook just adding some sudo in gem:
!sudo apt-get install ruby-full
!sudo apt-get install imagemagick
!sudo gem install prawn
!sudo gem install mini_magick
and it worked lol, it was my fault i just din't know how to install things

**Comment by Kartoffel0** [comment]
![StampNyaa_617_よつばスタジオ](https://github.com/Kartoffel0/Mokuro2Pdf/assets/99134182/9a308ebf-396a-426d-9ac4-ea69c33ae058)
